project:
  type: book

  pre-render:
    - R/create-labs-index.R

  resources:
    - LICENSES/*.txt

profile:
  default: html
  group:
    - [html, pdf, epub]

metadata-files:
  - _book-structure.yml

lang: es

language:
  crossref-ch-prefix: "Lab"

book:
  title: "Ingeniería aumentada por sistemas inteligentes"
  author: "Javier G. Grandez"
  output-file: "iasi-book-II"

copyright:
  holder: "Javier G. Grandez"
  year: 2026

license: "CC BY"

filters:
  - iasi-plantuml

filter-options:
  plantuml:
    enabled: true
    server: http://localhost:10025
    cache: true
    styles:
      - resources/plantuml/iasi.puml
